services:

  picocms:
    restart: always
    build: .
    image: gprevost/picocms
    command:
      "/run.sh"
    ports:
      - 9090:80
    volumes:
      - ./config:/home/sites/picocms/config
      - ./content:/home/sites/picocms/content
      - ./plugins:/home/sites/picocms/plugins
      - ./themes:/home/sites/picocms/themes
    networks:
      - picocms

networks:
  picocms:
    driver: bridge
